[package]
name = "array-utils"
description = "A no-std heapless set of array utils making use of const generics"
version = "0.0.0"
authors = ["Gijs Burghoorn <me@gburghoorn.com>"]
edition = "2018"
license = "MIT"

[dependencies]
